version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9
    resource_class: small
    working_directory: /go/src/github.com/pradeepg26/sifuconf
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go test -v ./...
      - store_artifacts:
          path: /tmp/test-results
          destination: raw-test-output
      - store_test_results:
          path: /tmp/test-results