version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9
    resource_class: small
    working_directory: /go/src/github.com/pradeepg26/sifuconf
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go get github.com/jstemmer/go-junit-report
      - run:
          name: Unit Tests
          command: |
              trap "go-junit-report </tmp/test-results/go-test.out > /tmp/test-results/go-test-report.xml" EXIT
              go test -v ./... | tee /tmp/test-results/go-test.out
            
            
      - store_artifacts:
          path: /tmp/test-results
          destination: raw-test-output
      - store_test_results:
          path: /tmp/test-results